import { GoogleGenAI } from '@google/genai';
import { DiffResult } from '../agents/DiffAgent';
import { ContextResult } from '../agents/ContextAgent';
import { MetadataResult } from '../agents/MetadataAgent';

export class GeminiEngine {
  private ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      console.warn('⚠️ GEMINI_API_KEY is not set. LLM analysis will fail.');
    }
    // Initialize the Gemini client
    this.ai = new GoogleGenAI({ apiKey });
  }

  async analyze(
    diff: DiffResult,
    context: ContextResult,
    metadata: MetadataResult
  ): Promise<string> {
    console.log('[GeminiEngine] Analyzing PR diff...');
    
    // Construct the prompt
    const prompt = `
You are an expert AI code reviewer. Please review the following Pull Request.

**PR Metadata:**
- Intent: ${metadata.intent}
- Complexity: ${metadata.complexity}
- Has Tests: ${metadata.hasTests ? 'Yes' : 'No'}

**Project Context:**
- Languages: ${context.languages.join(', ')}
- Frameworks/Tech: ${context.frameworks.join(', ')}

**Diff Stats:**
- Files Changed: ${diff.filesChanged}
- Insertions: ${diff.insertions}
- Deletions: ${diff.deletions}

**Raw Diff:**
\`\`\`diff
${diff.rawDiff.substring(0, 15000)} // Truncate if too long to save tokens
\`\`\`

Provide a concise, constructive code review. Point out bugs, security issues, performance problems, and style inconsistencies. Do not just summarize the diff. Focus on actionable feedback.
`;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: prompt,
      });

      return response.text || 'No review generated by the model.';
    } catch (error: any) {
      console.error('[GeminiEngine] Error generating review:', error);
      return '🤖 AI Review encountered an error during generation.';
    }
  }
}
