import { GoogleGenAI } from '@google/genai';
import { DiffResult } from '../agents/DiffAgent';
import { ContextResult } from '../agents/ContextAgent';
import { MetadataResult } from '../agents/MetadataAgent';

export class GeminiEngine {
  private ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      console.warn('⚠️ GEMINI_API_KEY is not set. LLM analysis will fail.');
    }
    // Initialize the Gemini client
    this.ai = new GoogleGenAI({ apiKey });
  }

  async analyze(
    diff: DiffResult,
    context: ContextResult,
    metadata: MetadataResult
  ): Promise<string> {
    console.log('[GeminiEngine] Analyzing PR diff...');

    // Construct the prompt
    const prompt = `
You are an expert, professional AI Code Reviewer. Your persona is a Senior Software Engineer providing a thorough, constructive, and polite code review.

**PR Metadata:**
- Intent: ${metadata.intent}
- Complexity: ${metadata.complexity}
- Has Tests: ${metadata.hasTests ? 'Yes' : 'No'}

**Project Context:**
- Languages: ${context.languages.join(', ')}
- Frameworks/Tech: ${context.frameworks.join(', ')}

**Diff Stats:**
- Files Changed: ${diff.filesChanged}
- Insertions: ${diff.insertions}
- Deletions: ${diff.deletions}

**Raw Diff:**
\`\`\`diff
${diff.rawDiff.substring(0, 15000)}
\`\`\`

**Instructions for your Review:**
1. **Greeting:** Start with a polite, professional greeting to the author.
2. **Summary:** Provide a concise 1-2 sentence summary of what this code change accomplishes.
3. **Praise:** Highlight at least one positive aspect of the code (e.g., good naming, clean logic, adding tests).
4. **Constructive Feedback:** If there are bugs, security issues, performance problems, or style inconsistencies, list them clearly using bullet points or a table. Be specific and actionable. If the code is perfect, state that explicitly.
5. **Formatting:** Use rich Markdown (bolding, lists, code blocks for suggestions) to make your review easy to read. Do NOT use generic headers like "Review:"—make it feel like a natural, high-quality human response.
`;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });

      return response.text || 'No review generated by the model.';
    } catch (error: any) {
      if (error.status === 400 || error.message?.includes('API key not valid')) {
        console.error('❌ [GeminiEngine] Error: Invalid API Key provided. Please check your .env file.');
      } else {
        console.error(`❌ [GeminiEngine] Error generating review: ${error.message || 'Unknown error'}`);
      }
      return '🤖 AI Review encountered an error during generation (e.g., Invalid API Key or Quota exceeded). Please check the server logs.';
    }
  }
}
