import { GoogleGenAI } from '@google/genai';
import { DiffResult } from '../agents/DiffAgent';
import { ContextResult } from '../agents/ContextAgent';
import { MetadataResult } from '../agents/MetadataAgent';

export class GeminiEngine {
  private ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      console.warn('⚠️ GEMINI_API_KEY is not set. LLM analysis will fail.');
    }
    // Initialize the Gemini client
    this.ai = new GoogleGenAI({ apiKey });
  }

  async analyze(
    diff: DiffResult,
    context: ContextResult,
    metadata: MetadataResult
  ): Promise<string> {
    console.log('[GeminiEngine] Analyzing PR diff...');
    
    // Construct the prompt
    const prompt = `
You are an expert software engineer reviewing a pull request.

Write a clear, concise, and professional code review that is easy for developers to scan and act on.

**PR Metadata:**
- Intent: ${metadata.intent}
- Complexity: ${metadata.complexity}
- Has Tests: ${metadata.hasTests ? 'Yes' : 'No'}

**Project Context:**
- Languages: ${context.languages.join(', ')}
- Frameworks/Tech: ${context.frameworks.join(', ')}

**Diff Stats:**
- Files Changed: ${diff.filesChanged}
- Insertions: ${diff.insertions}
- Deletions: ${diff.deletions}

**Raw Diff:**
\`\`\`diff
${diff.rawDiff.substring(0, 15000)}
\`\`\`

Guidelines:
- Do NOT include greetings or conversational filler.
- Start directly with a short summary (1–2 sentences) of what the change does.
- Highlight notable strengths briefly (only if meaningful).
- Focus on actionable feedback.

For issues:
- Clearly explain the problem (bug, performance, security, or readability).
- Provide exact corrected code using Markdown code blocks.
- Keep explanations short and precise (1–2 lines max).
- Only include fixes when necessary—avoid noise.

Formatting:
- Use clean Markdown (bullet points, short sections).
- Group issues logically if multiple exist.
- Avoid unnecessary headers or verbosity.
- Prioritize readability and developer efficiency.

Tone:
- Professional, direct, and constructive.
- No fluff, no repetition.
`;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });

      return response.text || 'No review generated by the model.';
    } catch (error: any) {
      if (error.status === 400 || error.message?.includes('API key not valid')) {
        console.error('❌ [GeminiEngine] Error: Invalid API Key provided. Please check your .env file.');
      } else if (error.status === 429) {
        console.error('❌ [GeminiEngine] Error: Quota exceeded or rate limited. Please check your plan limits.');
      } else {
        console.error(`❌ [GeminiEngine] Error generating review: ${error.message || 'Unknown error'}`);
      }
      return '🤖 AI Review encountered an error during generation (e.g., Invalid API Key or Quota exceeded). Please check the server logs.';
    }
  }
}
