import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import axios from 'axios';
import * as dotenv from 'dotenv';

dotenv.config();

const GITHUB_PAT = process.env.GITHUB_PAT;
if (!GITHUB_PAT) {
  console.error("❌ GITHUB_PAT environment variable is missing.");
  process.exit(1);
}

// Function to run shell commands
function runCmd(cmd: string) {
  console.log(`> ${cmd}`);
  return execSync(cmd, { encoding: 'utf-8', stdio: 'pipe' }).trim();
}

async function main() {
  try {
    console.log("🚀 Starting Trivial (Meaningless) PR Test");

    // 1. Get repository info from git remote
    const remoteOriginUrl = runCmd('git config --get remote.origin.url');
    // Extracts mathig12/codeReviewAgent from https://github.com/mathig12/codeReviewAgent.git
    const repoMatch = remoteOriginUrl.match(/github\.com[/:](.+?)(?:\.git)?$/);
    if (!repoMatch || !repoMatch[1]) {
      throw new Error(`Could not determine GitHub repository from remote URL: ${remoteOriginUrl}`);
    }
    const repoFullName = repoMatch[1];
    console.log(`📦 Repository: ${repoFullName}`);

    // 3. Make a trivial change that should be ignored by the AI
    const branchName = `test-trivial-${timestamp}`;
    runCmd(`git checkout -b ${branchName}`);
    console.log(`🌿 Created branch: ${branchName}`);

    const demoFilePath = path.join(__dirname, '..', `dummy-docs-${timestamp}.md`);
    const demoContent = `
# Dummy Documentation

This is a trivial file modification.
It should be completely ignored by the AI Review Agent because it is not a meaningful code change.
`;

    fs.writeFileSync(demoFilePath, demoContent.trim());
    console.log(`✍️ Created trivial markdown file: dummy-docs-${timestamp}.md`);

    // 4. Commit and push the change
    runCmd(`git add dummy-docs-${timestamp}.md`);
    runCmd(`git commit -m "docs: add dummy documentation ${timestamp}"`);
    console.log(`✅ Committed changes`);

    runCmd(`git push -u origin ${branchName}`);
    console.log(`☁️ Pushed branch ${branchName} to remote`);

    // 5. Raise a Pull Request via GitHub API
    console.log(`🐙 Creating Pull Request...`);
    const apiUrl = `https://api.github.com/repos/${repoFullName}/pulls`;
    
    // Check if we are currently branching off main or master
    let baseBranch = 'main';
    try {
      runCmd('git rev-parse --verify origin/main');
    } catch {
      try {
        runCmd('git rev-parse --verify origin/master');
        baseBranch = 'master'; // Fallback
      } catch {
        // If even master doesn't exist, try to use whatever branch we branched off of
        baseBranch = runCmd('git rev-parse --abbrev-ref HEAD');
      }
    }

    const prResponse = await axios.post(
      apiUrl,
      {
        title: `Automated Test PR ${timestamp}`,
        body: 'This PR was automatically generated by the E2E test script to verify the Code Review Agent.',
        head: branchName,
        base: baseBranch
      },
      {
        headers: {
          Authorization: `Bearer ${GITHUB_PAT}`,
          Accept: 'application/vnd.github.v3+json'
        }
      }
    );

    const prUrl = prResponse.data.html_url;
    console.log(`🎉 Success! Pull Request created at: ${prUrl}`);
    
    // Switch back to original branch
    runCmd(`git checkout ${baseBranch}`);
    console.log(`🔙 Switched back to ${baseBranch}`);
    
  } catch (error: any) {
    console.error('❌ Automation failed:', error.message || error);
    if (error.response?.data) {
      console.error('API Error Details:', error.response.data);
    }
  }
}

main();
