import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import axios from 'axios';
import * as dotenv from 'dotenv';

dotenv.config();

const GITHUB_PAT = process.env.GITHUB_PAT;
if (!GITHUB_PAT) {
  console.error("❌ GITHUB_PAT environment variable is missing.");
  process.exit(1);
}

// Function to run shell commands
function runCmd(cmd: string) {
  console.log(`> ${cmd}`);
  return execSync(cmd, { encoding: 'utf-8', stdio: 'pipe' }).trim();
}

async function main() {
  try {
    console.log("🚀 Starting Automated E2E PR Test");

    // 0. Capture current branch to switch back later
    const originalBranch = runCmd('git rev-parse --abbrev-ref HEAD');

    // 1. Get repository info from git remote
    const remoteOriginUrl = runCmd('git config --get remote.origin.url');
    const repoMatch = remoteOriginUrl.match(/github\.com[/:](.+?)(?:\.git)?$/);
    if (!repoMatch || !repoMatch[1]) {
      throw new Error(`Could not determine GitHub repository from remote URL: ${remoteOriginUrl}`);
    }
    const repoFullName = repoMatch[1];
    console.log(`📦 Repository: ${repoFullName}`);

    // 2. Create a new branch
    const timestamp = Date.now();
    const branchName = `test-auto-${timestamp}`;
    runCmd(`git checkout -b ${branchName}`);
    console.log(`🌿 Created branch: ${branchName}`);

    // 3. Make a meaningful code change - Pick a random dynamic scenario
    const scenarios = [
      {
        name: 'calculator',
        filePrefix: 'calculator',
        commitMsg: 'feat: add calculator utility module',
        content: `
/**
 * Simple calculator utility.
 * Added for testing the Code Review Agent's ability to catch bugs and bad practices.
 */
export class Calculator {
  public result: any; 

  constructor() {
    console.log("Calculator initialized");
  }

  add(a: number, b: number) {
    this.result = a + b;
    return this.result;
  }

  divide(a: number, b: number) {
    return a / b;
  }
  
  processData(data: any) {
    if (data == "100") {
      return true;
    }
    return false;
  }
}
`
      },
      {
        name: 'authenticator',
        filePrefix: 'auth-service',
        commitMsg: 'feat: implement basic auth service',
        content: `
/**
 * Authentication service.
 */
export class AuthService {
  private readonly SECRET = "my_super_secret_key_123";

  login(username: string, password: any) {
    if (username == "admin" && password == "admin123") {
      return this.generateToken(username);
    }
    return null; 
  }

  generateToken(user: string) {
    const token = user + "_" + this.SECRET + "_" + Date.now();
    return token;
  }
}
`
      },
      {
        name: 'data-fetcher',
        filePrefix: 'api-client',
        commitMsg: 'feat: add api client for user data',
        content: `
/**
 * API Client for fetching data.
 */
import axios from 'axios';

export async function fetchUserData(userId: string) {
  const response = await axios.get("https://api.example.com/users/" + userId);
  const data = response.data;
  data.processedAt = new Date().toISOString();
  return data;
}

fetchUserData("123");
`
      }
    ];

    const randomScenario = scenarios[Math.floor(Math.random() * scenarios.length)];
    if (!randomScenario) throw new Error("Could not select a random scenario");
    
    const fileName = `${randomScenario.filePrefix}-${timestamp}.ts`;
    const demoFilePath = path.join(__dirname, '..', 'src', fileName);
    
    fs.writeFileSync(demoFilePath, randomScenario.content.trim());
    console.log(`✍️ Created dynamic feature file (${randomScenario.name}): src/${fileName}`);

    // 4. Commit and push the change
    runCmd(`git add src/${fileName}`);
    runCmd(`git commit -m "${randomScenario.commitMsg} ${timestamp}"`);
    console.log(`✅ Committed changes`);

    runCmd(`git push -u origin ${branchName}`);
    console.log(`☁️ Pushed branch ${branchName} to remote`);

    // 5. Raise a Pull Request via GitHub API
    console.log(`🐙 Creating Pull Request...`);
    const apiUrl = `https://api.github.com/repos/${repoFullName}/pulls`;
    
    // Determine base branch (usually main or master)
    let baseBranch = 'main';
    try {
      runCmd('git rev-parse --verify origin/main');
    } catch {
      try {
        runCmd('git rev-parse --verify origin/master');
        baseBranch = 'master';
      } catch {
        baseBranch = originalBranch; // Fallback to whatever we started on
      }
    }

    const prResponse = await axios.post(
      apiUrl,
      {
        title: `Automated Test PR ${timestamp}`,
        body: 'This PR was automatically generated by the E2E test script to verify the Code Review Agent.',
        head: branchName,
        base: baseBranch
      },
      {
        headers: {
          Authorization: `Bearer ${GITHUB_PAT}`,
          Accept: 'application/vnd.github.v3+json'
        }
      }
    );

    const prUrl = prResponse.data.html_url;
    console.log(`🎉 Success! Pull Request created at: ${prUrl}`);
    
    // Switch back to original branch
    runCmd(`git checkout ${originalBranch}`);
    console.log(`🔙 Switched back to ${originalBranch}`);
    
  } catch (error: any) {
    console.error('❌ Automation failed:', error.message || error);
    if (error.response?.data) {
      console.error('API Error Details:', error.response.data);
    }
  }
}

main();
